### ISSUE TITLE
create figure to describe characteristics of the universe of private high schools

### ISSUE THREAD

**Issue by ozanj** [cyouh95/recruiting-chapter#11]
Hey @cyouh95 !

can you create a figure that shows the characteristics of the universe of private high schools [those that satisfy our criteria] on the dimensions of geographic region, religious affiliation, racial composition, academic reputation.

Why add such a figure: it will enable us to compare the characteristics of high schools that receive visits from particular colleges/universities [in the ego table figures] to the broader population of private high schools.

comparison to ego table figures:

- in ego table figures, there is one "row" for each permutation of university i and characteristic z
- in this figure, there is only one row for each characteristic

one potential concern: should private schools that enroll fewer students be given the same weight as private schools that enroll more students?

I think the solution to this concern is to create two versions of this figure: an unweighted version and a version that is weighted by relative number of 12th graders enrolled.

I think this weighted and unweighted version can be accomplished in a single figure. for example, imagine a figure with two columns where left column is unweighted and right column is enrollment weighted.

Use your discretion on figure layout. but keep in mind that the goal is to make it easy for reader to compare this figure to the ego table figures.

thank you!!!

**Comment by cyouh95** [comment]
[Here](https://github.com/cyouh95/recruiting-chapter/blob/c4903235ef3f1a3b4377972ab5a4d755471f75a9/assets/figures/plot_pss_universe.pdf)'s what this look like so far, but not too sure how to best format it. Because the bars for the 4 characteristics use different legends, I ended up grouping them so the weighted and unweighted are together for each plot.

The universe of private HS used is all 2017-18 PSS schools that fit our criteria + any schools we used from 2015-16 or 2013-14 data.
