### ISSUE TITLE
revisions to bar charts of ego graphs

### ISSUE THREAD

**Issue by ozanj** [cyouh95/recruiting-chapter#9]
cc: @irmacastaneda0822 

Crystal - some revisions to make to your beautiful bar charts of ego graphs, and then we'll tweet them out:

- on region, I want the order (left to right) as Northeast, Midwest, South, West
- on religion, use the new 4 category religion variable; and order of religion from left to right should be: Catholic, Christian, Other religion, non-sectarian
- add value labels to all categories (e.g., cl_lt10 becomes "Less than 10%")
- add number of private school visits in parentheses to the right of institution name, but maybe just on the charts on the left and not on charts on the right
- Revise chart captions to be succinct and descriptive
- Figure out some way to indicate which institutions belong in the same cluster and how to indicate what that means on caption
- figure out best file format for sharing on twitter, and output to that file format
- what is url for sharing on twitter? should we create tiny url or something? whatever is the best practice fore sharing stuff like this

no huge rush on this. we'll share when it's ready
-

**Comment by cyouh95** [comment]
Sorry this took a while! Changes are added to `tables.Rmd` (an example on last page [here](https://github.com/cyouh95/recruiting-chapter/blob/ef22aacc581051ca5840c68d07c3fc39435687d6/tables.pdf)) and plots are saved in the `figures` folder.

- For the plot captions, the current ones in the manuscript seems good to me - or do we want it even shorter?
- The univ clusters are indicated using boldface. Maybe we can indicate that in a footnote/comment below the caption (example in `tables.pdf` linked above)
- For sharing, maybe we can save a page of the manuscript PDF of the figure? That way it includes the caption/footnotes. PDF also seems like a good file format since it's better quality than a saved image.
- One option is to use Dropbox link for sharing (so we can modify PDF and the link won't change). Not too sure if we need tiny url or anything - is that just to shorten URL to not go over tweet character limit?
